import type { Metadata } from 'next';
import { Barlow } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const CurrentFont = Barlow({
  weight: '400',
  subsets: ['latin'],
});

const navigation = [
  { href: '/', label: 'Home' },
  { href: '/bakery', label: 'The Bakery' },
  { href: '/cafe', label: 'The Cafe' },
  { href: '/local', label: 'Little Local' },
  { href: '/foodtruck', label: 'The Food Truck' },
  { href: '/contact', label: 'Contact' },
];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={CurrentFont.className}>
        <div className='flex justify-center text-lg'>
          <button>
            <span>Join the Coffee Club ☕! 50% OFF FIRST ORDER!</span>
          </button>
        </div>
        <div className='flex w-4/5 m-auto align-center justify-between flex-nowrap'>
          <div className='text-4xl font-black tracking-wider'>
            <span>Golden Coffee</span>
          </div>
          <div>
            {navigation.map((nav) => (
              <Link
                className='mr-5 relative group'
                key={nav.label}
                href={nav.href}
              >
                {nav.label}
              </Link>
            ))}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
