import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const dm_sans = DM_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={dm_sans.className}>
        <div className='flex justify-center text-lg'>
          <button>
            <span>Join the Coffee Club ☕! 50% OFF FIRST ORDER!</span>
          </button>
        </div>
        <div>
          <div className='text-4xl font-extrabold'>Golden Coffee</div>
        </div>
        {children}
      </body>
    </html>
  );
}
